[package]
name = "hexacraft-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1.11.1"
jni = "0.21.1"
jni_fn = "0.1.2"
tokio = "1.49.0"
tokio-util = "0.7.18"
vorbis_rs = "0.5.5"
zeromq = { git = "https://github.com/zeromq/zmq.rs.git" }
